words = [
    "abate", "ambiguous", "anomaly", "assert", "bias",
    "coherent", "concede", "conventional", "corroborate", "detrimental",
    "diminish", "elaborate", "emulate", "empirical", "enhance",
    "equivocal", "exacerbate", "feasible", "hypothesis", "impartial",
    "implicit", "inference", "innovative", "integrity", "mitigate",
    "objective", "paradox", "plausible", "pragmatic", "prevalent",
    "profound", "refute", "relevant", "scrutinize", "significant",
    "skeptical", "subtle", "sustain", "theoretical", "transform",
    "undermine", "utilize", "validate", "viable", "volatile",
    "whereas", "ubiquitous", "contemporary", "nuance"
]

meanings = [
    "To become less intense or widespread",
    "Having more than one possible meaning; unclear",
    "Something that deviates from what is normal or expected",
    "To state a claim or belief confidently",
    "A tendency that prevents objective judgment",
    "Logical and consistent; easy to understand",
    "To admit something is true or valid",
    "Based on tradition or common practice",
    "To confirm or support with evidence",
    "Causing harm or damage",
    "To make smaller or less important",
    "To explain in greater detail",
    "To imitate or try to match",
    "Based on observation or experiment rather than theory",
    "To improve or increase quality or value",
    "Uncertain or open to multiple interpretations",
    "To make a problem or situation worse",
    "Possible and practical to accomplish",
    "A proposed explanation that can be tested",
    "Fair and unbiased",
    "Implied but not directly stated",
    "A conclusion drawn from evidence or reasoning",
    "Introducing new ideas or methods",
    "Honesty and strong moral principles",
    "To make something less severe or harmful",
    "Not influenced by personal feelings or opinions",
    "A statement that seems contradictory but may be true",
    "Seemingly reasonable or believable",
    "Focused on practical results rather than theory",
    "Widespread or commonly occurring",
    "Deep or intense in meaning or effect",
    "To prove something false",
    "Closely connected or applicable",
    "To examine closely and critically",
    "Important or meaningful",
    "Doubting or questioning accepted ideas",
    "Small but important details or distinctions",
    "To support or keep something going",
    "Based on ideas rather than real-world testing",
    "To change completely in form or nature",
    "To weaken or reduce effectiveness",
    "To make use of something",
    "To confirm the accuracy or legitimacy of something",
    "Capable of working successfully",
    "Unstable or likely to change suddenly",
    "In contrast or comparison with",
    "Present everywhere or very common",
    "Belonging to the present time",
    "A slight difference in meaning or expression"
]

example_sentences = [
    "The storm began to abate by morning.",
    "The question was ambiguous and confused many students.",
    "The low score was an anomaly compared to her usual performance.",
    "The author asserts that education is the key to progress.",
    "Media bias can influence public opinion.",
    "Her argument was coherent and well-organized.",
    "He conceded that the opposing argument was stronger.",
    "The study challenges conventional wisdom.",
    "The data corroborate the scientist’s theory.",
    "Lack of sleep is detrimental to academic performance.",
    "The importance of the discovery should not be diminished.",
    "The teacher asked the student to elaborate on her answer.",
    "Young artists often emulate their favorite painters.",
    "The conclusion was based on empirical evidence.",
    "Reading daily can enhance vocabulary skills.",
    "His response was equivocal and avoided a clear answer.",
    "Ignoring the issue may exacerbate the conflict.",
    "The plan seems feasible given the available resources.",
    "The scientist proposed a hypothesis to explain the results.",
    "A judge must remain impartial during the trial.",
    "There was an implicit assumption that everyone agreed.",
    "The inference was drawn from the author’s tone.",
    "The company is known for its innovative technology.",
    "Academic integrity is essential in research.",
    "Steps were taken to mitigate the risks.",
    "The report aimed to present an objective analysis.",
    "It is a paradox that freedom can require rules.",
    "Her explanation sounded plausible.",
    "He took a pragmatic approach to solving the problem.",
    "Smartphone use is prevalent among teenagers.",
    "The speech had a profound impact on the audience.",
    "The author attempts to refute the opposing viewpoint.",
    "Only relevant details should be included in the essay.",
    "Scientists scrutinize data before publishing results.",
    "There was a significant improvement in test scores.",
    "She was skeptical of the study’s conclusions.",
    "Understanding nuance is key in literary analysis.",
    "Funding is needed to sustain the program.",
    "The model is purely theoretical.",
    "Technology has transformed modern communication.",
    "Corruption can undermine public trust.",
    "Students should utilize available resources.",
    "The results validate the researcher’s claims.",
    "The proposal is viable in the long term.",
    "The market is highly volatile.",
    "Some students study alone, whereas others prefer groups.",
    "Social media is ubiquitous in modern society.",
    "The novel explores contemporary social issues.",
    "Word choice adds nuance to the argument."
]
